sonar.projectKey=aasthakumarii_go-devsecops-dashboard
sonar.organization=aasthakumarii

sonar.projectName=Go DevSecOps Dashboard

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.exclusions=reports/**,build/**

sonar.go.coverage.reportPaths=reports/sonar/coverage.out

sonar.sourceEncoding=UTF-8