name: Main DevSecOps Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      go-version: "1.23"

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      go-version: "1.23"

  sonarcloud:
    name: SonarCloud
    uses: ./.github/workflows/reusable-sonarcloud.yml
    with:
      go-version: "1.23"

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}